services:
  martian-robots-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - .:/app
    working_dir: /app
    command: php app.php input.txt

  martian-robots-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: php-test
    volumes:
      - .:/app
    working_dir: /app
    command: composer test